### ISSUE TITLE
Abordagem

### ISSUE THREAD

**Issue by edysegura** [HudsonLima/ecommerce#3]
Por qual o motivo o projeto não foi desenvolvido seguindo a abordagem ensinado na disciplina DM104 que separa o front-end do back-end através de serviços REST? @HudsonLima

**Comment by HudsonLima** [comment]
Olá, Edy! Obrigado pela pergunta.

Como não havia trabalhado ainda com REST, tive dificuldade no andamento do projeto. Nunca havia trabalhado também com  PHP.

Li material sobre Loja Virtual em PHP na internet, o que me ajudou bastante, e fiquei  satisfeito em desenvolver aplicação com Back-End em PHP (Coisa que nunca tinha feito), mesmo que sem REST. 

Você não considerou em nada o primeiro trabalho que fiz? (O CRUD em PHP que constava no PDF)

Obrigado, cara! 
@edysegura
